export enum ReportType {
  GROUP = 'GROUP',
  GROUP_COMMENT = 'GROUP_COMMENT',
  GROUP_REPLY = 'GROUP_REPLY',
  GROUP_BOARD = 'GROUP_BOARD',
  GROUP_BOARD_COMMENT = 'GROUP_BOARD_COMMENT',
  GROUP_BOARD_REPLY = 'GROUP_BOARD_REPLY',
  COMMUNITY = 'COMMUNITY',
  COMMUNITY_COMMENT = 'COMMUNITY_COMMENT',
  COMMUNITY_REPLY = 'COMMUNITY_REPLY',
}
